// apps/next-chapter-vue/src/pages/Shelf.vue
<script setup lang="ts">
import { watch } from "vue";
import { useRoute, useRouter } from "vue-router";
import { useQuery } from "@tanstack/vue-query";
import { toast } from "vue-sonner";
import { api } from "@/trpc";
import BaseLayout from "@/layouts/BaseLayout.vue";
import { BookListShelf, CardEmptyShelf } from "@/components";

const route = useRoute();
const router = useRouter();
const { id } = route.params;

const shelfId = typeof id === "string" ? id : "";

const {
  data: shelfInfo,
  isError: isShelfError,
  isLoading: isShelfLoading,
} = useQuery({
  queryKey: ["shelf", id],
  queryFn: () => api.shelf.get.query(shelfId),
});

const {
  isError: isBooksError,
  data: books,
  isLoading: isBooksLoading,
} = useQuery({
  queryKey: ["books", id],
  queryFn: () => api.book.getBooksInShelf.query(shelfId),
});

watch([isShelfError, isBooksError], ([shelfIsError, booksIsError]) => {
  if (shelfIsError || booksIsError) {
    toast.error("Failed to fetch books");
    router.push("/");
  }
});
</script>

<template>
  <BaseLayout>
    <p v-if="isShelfLoading || isBooksLoading">Loading...</p>
    <p v-if="isShelfError || isBooksError">Error...</p>
    <BookListShelf
      v-if="!isShelfLoading && !isBooksLoading && !isBooksError"
      :type="shelfInfo?.type || ''"
      :books="books || []"
    />
    <CardEmptyShelf
      v-if="
        !isShelfLoading && !isBooksLoading && !isBooksError && !books?.length
      "
    />
  </BaseLayout>
</template>

// apps/next-chapter-react/src/pages/Shelf.tsx
import { FC, useEffect } from "react";
import { BaseLayout } from "layouts";
import { useParams, useNavigate } from "react-router-dom";
import { BookListShelf, CardEmptyShelf } from "components";
import { api } from "trpc";
import toast from "react-hot-toast";

const Shelf: FC = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  const { data: shelfInfo } = api.shelf.get.useQuery(id || "");
  const {
    data: books,
    isLoading,
    isError,
    error,
  } = api.book.getBooksInShelf.useQuery(id || "");

  useEffect(() => {
    if (isError) {
      toast.error(error.message);
      navigate("/");
    }
  }, [isError]);

  return (
    <BaseLayout>
      {isLoading && <p>Loading...</p>}

      {isError && <p>Error...</p>}

      {!isLoading && !isError && books && (
        <BookListShelf type={shelfInfo?.type || ""} books={books} />
      )}

      {!isLoading && !isError && books?.length === 0 && <CardEmptyShelf />}
    </BaseLayout>
  );
};

export default Shelf;
