// apps/next-chapter-vue/src/components/Modal/ModalRemoveBook.vue
<script setup lang="ts">
import { api } from "@/trpc";
import { toast } from "vue-sonner";
import { useMutation, useQueryClient } from "@tanstack/vue-query";
import { emptyFunction } from "@/utils/functions";

export interface ModalRemoveBookProps {
  opened: boolean;
  handlers: {
    open: () => void;
    close: () => void;
  };
  bookId: string;
  title: string;
}

const { opened, bookId, title, handlers } = defineProps<ModalRemoveBookProps>();
const queryClient = useQueryClient();

const open = handlers?.open || emptyFunction;
const close = handlers?.close || emptyFunction;

const handlerFunctions = {
  open,
  close,
};

const { mutateAsync: removeBook, isPending } = useMutation({
  mutationFn: api.book.delete.mutate,
  onSuccess: async () => {
    toast.success("Book removed successfully");
    queryClient.invalidateQueries({ queryKey: ["shelves"] });
    queryClient.invalidateQueries({ queryKey: ["books"] });
  },
});

const handleRemove = async () => {
  try {
    await removeBook(bookId);
  } catch (err) {
    toast.error("Failed to remove book");
  } finally {
    handlers.close();
  }
};
</script>

<template>
  <VDialog
    :modelValue="opened"
    class="max-w-2xl"
    @update:modelValue="handlers.close"
  >
    <VCard>
      <div>
        <h2 class="text-primary">{{ title }}</h2>
        <p class="mt-2">Are you sure to delete this book from your shelf?</p>
        <div class="flex justify-end mt-4 gap-x-2">
          <VBtn
            color="primary"
            :disabled="isPending"
            @click="handlerFunctions.close"
            >No</VBtn
          >
          <VBtn color="error" :disabled="isPending" @click="handleRemove"
            >Yes</VBtn
          >
        </div>
      </div>
    </VCard>
  </VDialog>
</template>

// apps/next-chapter-react/src/components/Modal/ModalRemoveBook.tsx
import { FC } from "react";
import { Modal, Box, Typography, Button } from "@mui/material";
import { api } from "trpc";
import toast from "react-hot-toast";

interface ModalRemoveBookProps {
  opened: boolean;
  handlers: {
    open: () => void;
    close: () => void;
  };
  bookId: string;
  title: string;
}

const ModalRemoveBook: FC<ModalRemoveBookProps> = ({
  opened,
  handlers,
  bookId,
  title,
}) => {
  const utils = api.useUtils();

  const { mutateAsync: removeBook, isLoading } = api.book.delete.useMutation();

  const handleRemove = async () => {
    try {
      await removeBook(bookId);
      await utils.shelf.getAll.invalidate();
      toast.success("Book removed successfully");
    } catch (err) {
      toast.error("Failed to remove book");
    } finally {
      handlers.close();
    }
  };

  return (
    <Modal
      open={opened}
      aria-labelledby="remove-book-modal"
      aria-describedby="remove-book-modal"
      onClose={handlers.close}
    >
      <Box className="modal">
        <Typography
          className="text-primary-main"
          id="modal-title"
          variant="h6"
          component="h2"
        >
          {title}
        </Typography>

        <Typography className="mt-2">
          Are you sure to delete this book from your shelf?
        </Typography>

        <div className="mt-4 flex gap-4 justify-end">
          <Button onClick={handlers.close}>No</Button>
          <Button
            disabled={isLoading}
            variant="contained"
            color="error"
            onClick={handleRemove}
          >
            Yes
          </Button>
        </div>
      </Box>
    </Modal>
  );
};

export default ModalRemoveBook;
