// apps/next-chapter-react/src/pages/Search.tsx
import React, { FC, useState, useRef } from "react";
import { BaseLayout } from "layouts";
import { Box, TextField, CircularProgress } from "@mui/material";
import { useQuery } from "@tanstack/react-query";
import { searchBooks } from "@acme/google-books";
import { Clear, Search as SearchIcon } from "@mui/icons-material";
import { BookListSearch } from "components";

const Search: FC = () => {
  const [query, setQuery] = useState("");
  const queryRef = useRef<HTMLInputElement | null>(null);

  const {
    data: books,
    isFetching,
    isError,
  } = useQuery(
    ["books", query],
    () =>
      searchBooks({
        query: query,
      }),
    {
      enabled: Boolean(query),
      refetchOnWindowFocus: false,
      keepPreviousData: true,
    },
  );

  const handleSearch = (
    e: React.FormEvent<HTMLFormElement> | React.MouseEvent,
  ) => {
    e.preventDefault();
    setQuery(queryRef?.current?.value || "");
  };

  const clear = () => {
    setQuery("");
    if (queryRef.current) {
      queryRef.current.value = "";
    }
  };

  return (
    <BaseLayout>
      <Box
        onSubmit={handleSearch}
        component="form"
        className="flex gap-x-2 max-w-lg w-full"
      >
        <TextField
          autoFocus
          fullWidth
          size="small"
          label="Search Books"
          inputRef={queryRef}
          InputProps={{
            endAdornment: (
              <div className="flex items-center gap-x-2">
                <Clear
                  className="cursor-pointer text-primary-main text-lg"
                  onClick={clear}
                />
                <SearchIcon
                  className="cursor-pointer text-primary-main text-lg"
                  onClick={handleSearch}
                />
              </div>
            ),
          }}
        />
        <div className="w-[10%]">
          {isFetching && <CircularProgress color="primary" />}
        </div>
      </Box>

      {!isFetching && !isError && books?.items && (
        <BookListSearch books={books.items} />
      )}
    </BaseLayout>
  );
};

export default Search;

// apps/next-chapter-vue/src/pages/Search.vue
<script setup lang="ts">
import { ref } from "vue";
import { useQuery } from "@tanstack/vue-query";
import { searchBooks } from "@acme/google-books";
import { BookListSearch } from "@/components";
import { BaseLayout } from "@/layouts";

const searchField = ref("");
const query = ref("");

const {
  data: books,
  isLoading,
  isError,
  refetch,
} = useQuery({
  queryKey: ["books", query],
  queryFn: () => searchBooks({ query: query.value }),
  enabled: Boolean(query.value),
  refetchOnWindowFocus: false,
});

const handleSearch = async () => {
  if (searchField.value) {
    query.value = searchField.value;
    await refetch();
  }
};

const clear = () => {
  searchField.value = "";
  query.value = "";
};
</script>

<template>
  <BaseLayout :require-auth="true">
    <form @submit.prevent="handleSearch" class="flex gap-x-2 max-w-lg w-full">
      <VTextField
        density="compact"
        variant="outlined"
        color="primary"
        autoFocus
        fullWidth
        label="Search Books"
        v-model="searchField"
        class="w-full"
      >
        <template #append-inner>
          <div class="flex items-center gap-x-2">
            <VIcon
              icon="mdi-close"
              class="cursor-pointer text-primary-main text-lg"
              @click="clear"
            />
            <VIcon
              icon="mdi-magnify"
              class="cursor-pointer text-primary-main text-lg"
              @click="handleSearch"
            />
          </div>
        </template>
      </VTextField>
      <div class="w-[10%] h-full">
        <VProgressCircular
          size="40"
          indeterminate
          v-if="isLoading"
          color="primary"
        />
      </div>
    </form>

    <BookListSearch
      v-if="!isLoading && !isError && books?.items"
      :books="books.items"
    />
  </BaseLayout>
</template>
