// apps/next-chapter-react/src/components/BookList/BookListSearch.tsx
import { Item } from "@acme/google-books";
import { FC } from "react";
import { CardSearch } from "components/Card";

interface BookListSearchProps {
  books: Item[];
}

const BookListSearch: FC<BookListSearchProps> = ({ books }) => {
  return (
    <div className="grid gap-3 sm:gap-6 grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 py-5">
      {books.map((book) => (
        <CardSearch key={book.id} item={book} />
      ))}
    </div>
  );
};

export default BookListSearch;

// apps/next-chapter-vue/src/components/BookList/BookListSearch.vue
<script setup lang="ts">
import { SearchResults } from "@acme/google-books";
import { CardSearch } from "../Card";

export interface BookListShelfProps {
  books?: SearchResults["items"];
}

const { books } = defineProps<BookListShelfProps>();
</script>

<template>
  <div
    class="grid gap-3 sm:gap-6 grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 py-3"
  >
    <CardSearch v-for="book in books" :key="book.id" :item="book" />
  </div>
</template>
