// apps/next-chapter-react/src/components/BookList/BookListShelfPreview.tsx
import { Typography } from "@mui/material";
import { FC } from "react";
import { Book } from "@acme/db";
import { CardShelf, CardEmptyShelf } from "components/Card";
import { Link } from "react-router-dom";

interface CardShelfProps {
  title: string;
  books: Book[];
  shelfId: string;
}

const BookListShelfPreview: FC<CardShelfProps> = ({
  books,
  title,
  shelfId,
}) => {
  return (
    <div className="flex flex-col gap-y-2">
      <div className="flex justify-between items-center">
        <Typography className="text-2xl font-bold">{title}</Typography>

        <Link
          to={`/shelf/${shelfId}`}
          className="text-primary-main font-semibold h-full"
        >
          View all
        </Link>
      </div>
      <div className="flex overflow-x-auto gap-x-3 snap-x snap-mandatory">
        {books.length === 0 && <CardEmptyShelf />}
        {books.map((book) => (
          <CardShelf key={book.id} book={book} />
        ))}
      </div>
    </div>
  );
};

export default BookListShelfPreview;

// apps/next-chapter-vue/src/components/BookList/BookListShelfPreview.vue
<script setup lang="ts">
import { Book } from "@acme/db";
import { CardShelf, CardEmptyShelf } from "../Card";

interface CardShelfProps {
  title: string;
  books: Book[];
  shelfId: string;
}

const { title, books, shelfId } = withDefaults(
  defineProps<CardShelfProps>(),
  {}
);
</script>

<template>
  <div class="flex flex-col gap-y-2">
    <div class="flex justify-between items-center">
      <h2 class="text-2xl font-bold text-primary">{{ title }}</h2>
      <router-link :to="`/shelf/${shelfId}`" class="text-primary font-semibold h-full">View all</router-link>
    </div>
    <div class="flex overflow-x-auto gap-x-3 snap-x snap-mandatory">
      <CardEmptyShelf v-if="books.length === 0" />
      <CardShelf v-for="book in books" :key="book.id" :book="book" />
    </div>
  </div>
</template>
