// apps/next-chapter-react/src/components/TextAreaForm/TextAreaForm.tsx
import { TextField, Button, TextFieldProps } from "@mui/material";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { zodResolver } from "@hookform/resolvers/zod";
import clsx from "clsx";
import AddIcon from "@mui/icons-material/Add";

type TextFieldPropsWithoutOnSubmit = Omit<TextFieldProps, "onSubmit">;

type TextAreaFormProps = TextFieldPropsWithoutOnSubmit & {
  type: "CREATE" | "EDIT";
  onSubmit: (description: string) => Promise<void> | void;
  onCancel?: () => void;
  initialValue?: string;
  name: string;
  isLoading?: boolean;
};

const validateSchema = z.object({
  description: z
    .string()
    .min(1, { message: "Content cannot be empty" })
    .max(500, { message: "Content cannot exceed 500 characters" }),
});

type FormValues = z.infer<typeof validateSchema>;

const TextAreaForm: React.FC<TextAreaFormProps> = ({
  type,
  onSubmit,
  onCancel = () => {},
  name,
  initialValue,
  isLoading = false,
  ...props
}) => {
  const {
    register,
    handleSubmit,
    formState: { errors },
    reset,
  } = useForm<FormValues>({
    resolver: zodResolver(validateSchema),
    defaultValues: { description: initialValue },
  });

  const isCreate = type === "CREATE";
  const isEdit = type === "EDIT";

  const onFormSubmit = (data: FormValues) => {
    onSubmit(data.description);

    if (isCreate) {
      reset();
    }
  };

  return (
    <form
      onSubmit={handleSubmit(onFormSubmit)}
      className="flex flex-col space-y-4"
    >
      <TextField
        autoFocus={isEdit}
        multiline
        rows={4}
        {...register("description")}
        placeholder={
          isCreate ? `Write a new ${name}...` : `Edit your ${name}...`
        }
        className={clsx(props.className, "w-full")}
        error={!!errors.description}
        helperText={errors.description?.message}
        {...props}
      />
      <div className="flex justify-end gap-x-2">
        {isEdit && (
          <Button
            onClick={() => onCancel()}
            color="primary"
            className="self-start"
            size="small"
          >
            Cancel
          </Button>
        )}
        <Button
          disabled={isLoading}
          type="submit"
          variant="contained"
          color="primary"
          className="self-start"
          size="small"
          startIcon={<AddIcon />}
        >
          {isCreate ? `Create ${name}` : `Save ${name}`}
        </Button>
      </div>
    </form>
  );
};

export default TextAreaForm;

// apps/next-chapter-vue/src/components/TextAreaForm.vue
<script setup lang="ts">
import { useForm } from "vee-validate";
import { toTypedSchema } from "@vee-validate/zod";
import { z } from "zod";

export interface TextAreaFormProps {
  type: "CREATE" | "EDIT";
  onSubmit: (description: string) => Promise<void> | void;
  onCancel?: () => void;
  name: string;
  initialValue?: string;
  isLoading?: boolean;
}

// Define vue props
const { type, onSubmit, onCancel, name, initialValue, isLoading } =
  defineProps<TextAreaFormProps>();

const validateSchema = z.object({
  description: z
    .string()
    .min(1, { message: "Content cannot be empty" })
    .max(500, { message: "Content cannot exceed 500 characters" }),
});

type FormValues = z.infer<typeof validateSchema>;



const { errors, resetForm, handleSubmit, defineField } = useForm<FormValues>({
  initialValues: { description: initialValue ?? "" },
  validationSchema: toTypedSchema(validateSchema),
})

const isCreate = type === "CREATE";
const isEdit = type === "EDIT";


const submit = handleSubmit(values => {
  onSubmit(values.description)
  if (isCreate) {
    resetForm();
  }
})

const [description] = defineField("description")
</script>

<template>
  <form @submit.prevent="submit" class="flex flex-col space-y-4">
    <VTextarea :autofocus="isEdit" rows="4" :placeholder="isCreate ? `Write a new ${name}...` : `Edit your ${name}...`
      " :error-messages="errors.description" class="w-full" v-model="description">
    </VTextarea>
    <div class="flex justify-end gap-x-2">
      <VBtn size="small" v-if="isEdit" @click="onCancel" color="primary" class="self-start" variant="tonal">
        Cancel</VBtn>
      <VBtn size="small" :disabled="isLoading" type="submit" color="primary" class="self-start">
        <VIcon icon="mdi-plus" />
        {{ isCreate ? `Create ${name}` : `Save ${name}` }}
      </VBtn>
    </div>
  </form>
</template>
